### ISSUE TITLE
Mapping network

### ISSUE THREAD

**Issue by sidmani** [lucidrains/pi-GAN-pytorch#2]
Hi, I was looking at your code (I'm also thinking of implementing pi-gan) and had questions about the mapping network.
- What is the idea behind the EqualLinear module?
- Why are you normalizing the latent vector before passing it through the network?

As far as I can tell neither of these steps is mentioned in the paper so if you have another source for those steps that would be really helpful. Thanks!

**Comment by lucidrains** [comment]
@sidmani Hey Sid! Glad to meet someone else fascinated with the intersection of Nerf and GANs! I actually copied the mapping network code from my stylegan2 implementation. I'll correct it to match the paper's this week, after I code up the progressive growing part of the discriminator

**Comment by sidmani** [comment]
Great, I haven't read stylegan2 yet so I'll take a look.
